name: "Deploy application in multi env"
on:
  workflow_dispatch: # to manually run this workflow
  
jobs:
  DEVELOPMENT:
    name: Deploy in DEV
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v3
      - name: Run a script
        run: |
          echo "${{ vars.ENV_NAME }}"

  QUALITYANALYSIS:
    name: Deploy in QA
    runs-on: ubuntu-latest
    environment: QA
    needs: DEVELOPMENT
    steps:
      - uses: actions/checkout@v3
      - name: Run a script
        run: |
          echo "${{ vars.ENV_NAME }}"
          
  PRODUCTION:
    name: Deploy in PROD
    runs-on: ubuntu-latest
    environment: PROD    
    needs: QUALITYANALYSIS
    steps:
      - uses: actions/checkout@v3
      - name: Run a script
        run: |
          echo "${{ vars.ENV_NAME }}"          
